spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parser
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update

rewriteBatchedStatements: true
cachePrepStmts: true
useServerPrepStmts: true





